package environment_test

import (
	"testing"

	"tsumegolang/game/starshot/def"
	"tsumegolang/game/starshot/entity/environment"
	"tsumegolang/game/starshot/testutil"
)

func TestSpaceImplementsEntity(t *testing.T) {
	scene := testutil.NewMockScene()
	space := environment.NewSpace(0.05, scene)

	var _ def.Entity = space

	// Verify all interface methods work
	if got := space.Type(); got != def.EntityTypeEnvironment {
		t.Errorf("Type() = %v, want %v", got, def.EntityTypeEnvironment)
	}

	x, y := space.Location()
	if x != 0 || y != 0 {
		t.Errorf("Location() = (%d,%d), want (0,0)", x, y)
	}

	w, h := space.Dimensions()
	if w != def.ScreenWidth || h != def.ScreenHeight {
		t.Errorf("Dimensions() = (%d,%d), want (%d,%d)", w, h, def.ScreenWidth, def.ScreenHeight)
	}

	if space.CanBeRemoved() {
		t.Error("Space should never be removed")
	}

	if space.BoundingBoxOverlaps(space) {
		t.Error("Space should not overlap anything")
	}
}

func TestLayerSizeAndSpeed(t *testing.T) {
	testCases := []struct {
		layer     environment.Layer
		wantSize  int
		wantSpeed int
	}{
		{environment.Close, 5, 5},
		{environment.Mid, 3, 3},
		{environment.Far, 2, 1},
	}

	for _, tc := range testCases {
		t.Run(tc.layer.String(), func(t *testing.T) {
			gotSize, gotSpeed := environment.SizeAndSpeedForLayer(tc.layer)

			if gotSize != tc.wantSize {
				t.Errorf("size = %d, want %d", gotSize, tc.wantSize)
			}

			if gotSpeed != tc.wantSpeed {
				t.Errorf("speed = %d, want %d", gotSpeed, tc.wantSpeed)
			}
		})
	}
}

func TestLayerSizeSpeedRelationships(t *testing.T) {
	closeSize, closeSpeed := environment.SizeAndSpeedForLayer(environment.Close)
	midSize, midSpeed := environment.SizeAndSpeedForLayer(environment.Mid)
	farSize, farSpeed := environment.SizeAndSpeedForLayer(environment.Far)

	// Verify size ordering
	if !(closeSize >= midSize && midSize >= farSize) {
		t.Errorf("Size ordering broken: Close=%d, Mid=%d, Far=%d", closeSize, midSize, farSize)
	}

	// Verify speed ordering
	if !(closeSpeed >= midSpeed && midSpeed >= farSpeed) {
		t.Errorf("Speed ordering broken: Close=%d, Mid=%d, Far=%d", closeSpeed, midSpeed, farSpeed)
	}

	// Verify minimum size for visibility
	if farSize < 1 {
		t.Errorf("Far layer size %d is too small (invisible)", farSize)
	}
}

func TestSpaceGeneratesStars(t *testing.T) {
	scene := testutil.NewMockScene()
	space := environment.NewSpace(0.5, scene) // High density for reliable test

	initialCount := scene.EntityCount()

	// Call Act() multiple times
	for i := 0; i < 100; i++ {
		space.Act(scene)
	}

	got := scene.EntityCount()

	if got <= initialCount {
		t.Errorf("stars generated = %d, want > %d", got, initialCount)
	}
}

func TestAllLayersGenerate(t *testing.T) {
	scene := testutil.NewMockScene()
	space := environment.NewSpace(0.5, scene) // High density

	// Generate many stars
	for i := 0; i < 500; i++ {
		space.Act(scene)
	}

	// Count stars by size (proxy for layer)
	closeSize, _ := environment.SizeAndSpeedForLayer(environment.Close)
	midSize, _ := environment.SizeAndSpeedForLayer(environment.Mid)
	farSize, _ := environment.SizeAndSpeedForLayer(environment.Far)

	closeSeen := 0
	midSeen := 0
	farSeen := 0

	for _, entity := range scene.GetEntities() {
		w, _ := entity.Dimensions()
		switch w {
		case closeSize:
			closeSeen++
		case midSize:
			midSeen++
		case farSize:
			farSeen++
		}
	}

	if closeSeen == 0 {
		t.Error("No Close layer stars generated")
	}
	if midSeen == 0 {
		t.Error("No Mid layer stars generated")
	}
	if farSeen == 0 {
		t.Error("No Far layer stars generated")
	}

	t.Logf("Generated: Close=%d, Mid=%d, Far=%d", closeSeen, midSeen, farSeen)
}

func TestNewStarsStartAboveScreen(t *testing.T) {
	scene := testutil.NewMockScene()
	// Use density 0 to avoid seeding, then use high density for generation
	space := environment.NewSpace(0, scene)

	// Manually set density high for Act() calls
	// (We'd need to expose this or use a different approach)
	// For now, create a new space with high density after initial seeding
	scene = testutil.NewMockScene()
	space = environment.NewSpace(0.5, scene)

	// Clear seeded stars to test only Act()-generated stars
	initialCount := scene.EntityCount()

	// Generate new stars via Act()
	for range 100 {
		space.Act(scene)
	}

	// Check only stars added after seeding
	newStarsChecked := 0
	for i := initialCount; i < scene.EntityCount(); i++ {
		entity := scene.GetEntities()[i]
		if entity.Type() != def.EntityTypeBackground {
			continue
		}

		_, y := entity.Location()
		if y >= 0 {
			t.Errorf("Star %d (generated by Act) at y=%d, want < 0 to avoid pop-in", i, y)
		}
		newStarsChecked++
	}

	if newStarsChecked == 0 {
		t.Error("No new stars generated by Act() to test")
	}
}

func TestStarDensityAffectsGeneration(t *testing.T) {
	iterations := 200

	// Low density
	sceneLow := testutil.NewMockScene()
	spaceLow := environment.NewSpace(0.01, sceneLow)
	for i := 0; i < iterations; i++ {
		spaceLow.Act(sceneLow)
	}

	// High density
	sceneHigh := testutil.NewMockScene()
	spaceHigh := environment.NewSpace(0.10, sceneHigh)
	for i := 0; i < iterations; i++ {
		spaceHigh.Act(sceneHigh)
	}

	got := sceneHigh.EntityCount()
	baseline := sceneLow.EntityCount()

	if got <= baseline {
		t.Errorf("high density stars = %d, want > %d (low density)", got, baseline)
	}

	t.Logf("Low density (0.01): %d stars, High density (0.10): %d stars", baseline, got)
}

func TestInitialSeedingCreatesStars(t *testing.T) {
	scene := testutil.NewMockScene()

	// NewSpace should seed initial stars
	_ = environment.NewSpace(0.05, scene)

	got := scene.EntityCount()
	if got == 0 {
		t.Error("initial stars = 0, want > 0")
	}

	t.Logf("Initial seeding created %d stars", got)
}

func TestSeededStarsCoverScreen(t *testing.T) {
	scene := testutil.NewMockScene()

	// High density to ensure coverage
	_ = environment.NewSpace(0.2, scene)

	// Check that stars are distributed across Y range
	minY := scene.Height()
	maxY := 0

	for _, entity := range scene.GetEntities() {
		if entity.Type() != def.EntityTypeBackground {
			continue
		}
		_, y := entity.Location()
		if y < minY {
			minY = y
		}
		if y > maxY {
			maxY = y
		}
	}

	got := maxY - minY
	want := int(float64(scene.Height()-1) * 0.8) // At least 80% coverage

	if got < want {
		t.Errorf("Y range = %d, want >= %d (80%% of screen height)", got, want)
	}

	t.Logf("Seeded stars Y range: %d to %d (range=%d)", minY, maxY, got)
}

func TestStarColorsAreValid(t *testing.T) {
	scene := testutil.NewMockScene()
	space := environment.NewSpace(0.5, scene)

	// Generate many stars
	for i := 0; i < 1000; i++ {
		space.Act(scene)
	}

	invalidCount := 0
	for _, entity := range scene.GetEntities() {
		if entity.Type() != def.EntityTypeBackground {
			continue
		}

		// We can't directly access color from the interface, but we can verify
		// the entity was created successfully and has valid dimensions
		w, h := entity.Dimensions()
		if w <= 0 || h <= 0 {
			invalidCount++
		}
	}

	if invalidCount > 0 {
		t.Errorf("Found %d stars with invalid dimensions", invalidCount)
	}
}
